# CircleCI Configuration File
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.2.2
      - image: postgres:14.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: personal_blog_test
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Wait for PostgreSQL
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 5432 && echo "PostgreSQL is up and running" && break
              echo "Waiting for PostgreSQL..."
              sleep 5
            done

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Clear coverage data
          command: rm -rf coverage

      - run:
          name: Run RSpec Tests
          command: bundle exec rspec

      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
