# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2 # Substitua pela versão do Ruby que você está usando
    steps:
      - checkout
      - run: bundle install

      - run:
          name: Run tests
          command: bundle exec rspec # ou o comando que você usa para rodar seus testes

      - store_artifacts:
          path: coverage

