name: Ruby on Rails CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: personal_blog_test
        ports:
          - 5432:5432


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      
    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:test:prepare

    - name: Run tests
      run: |
        bundle exec rspec

