name: Ruby on Rails Specs

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true 

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      
    - name: Set up database
      run: |
        sleep 5
        bundle exec rake db:create RAILS_ENV=test
        bundle exec rake db:migrate RAILS_ENV=test


    - name: Run tests
      run: |
        bundle exec rspec
