name: Ruby on Rails Specs

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.9
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      
    - name: Set up database
      run: |
        sleep 5
        bundle exec rails db:migrate RAILS_ENV=test

    - name: Run tests
      run: |
        bundle exec rspec
